const SITE_URL = 'https://lucadauphin.ch';

const SWISS_CANTONS = [
  'Aargau',
  'Appenzell Innerrhoden',
  'Appenzell Ausserrhoden',
  'Basel-Landschaft',
  'Basel-Stadt',
  'Bern',
  'Fribourg',
  'Genève',
  'Glarus',
  'Graubünden',
  'Jura',
  'Luzern',
  'Neuchâtel',
  'Nidwalden',
  'Obwalden',
  'Schaffhausen',
  'Schwyz',
  'Solothurn',
  'St. Gallen',
  'Thurgau',
  'Ticino',
  'Uri',
  'Valais',
  'Vaud',
  'Zug',
  'Zürich',
];

const SWISS_CITIES = [
  'Genève',
  'Lausanne',
  'Zürich',
  'Bern',
  'Basel',
  'Lugano',
  'Sion',
  'Fribourg',
  'Neuchâtel',
  'Luzern',
];

export const localBusiness = {
  '@context': 'https://schema.org',
  '@type': 'FoodEstablishment',
  additionalType: 'https://schema.org/Caterer',
  '@id': `${SITE_URL}/#business`,
  name: 'LD',
  alternateName: 'LD Traiteur',
  description:
    "Service traiteur événementiel à Genève. Cuisine du monde, fusion créative pour vos événements d'entreprise de 50 à 300 personnes.",
  url: SITE_URL,
  logo: `${SITE_URL}/images/logo-black.webp`,
  image: `${SITE_URL}/images/logo-black.webp`,
  telephone: '+41786197822',
  email: 'info@lucadauphin.ch',
  foundingDate: '2025',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Chemin de Champ-Claude 10',
    postalCode: '1214',
    addressLocality: 'Vernier',
    addressRegion: 'GE',
    addressCountry: 'CH',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: 46.2107,
    longitude: 6.085,
  },
  areaServed: [
    { '@type': 'Country', name: 'Switzerland' },
    ...SWISS_CANTONS.map((c) => ({ '@type': 'AdministrativeArea', name: c })),
    ...SWISS_CITIES.map((c) => ({ '@type': 'City', name: c })),
  ],
  knowsLanguage: ['fr', 'it', 'en', 'de'],
  serviceType: [
    "Événements d'entreprise",
    'Mariages',
    'Réceptions privées',
    'Institutionnel et associatif',
    'Buffets événementiels',
    'Service à l’assiette',
  ],
  founder: {
    '@type': 'Person',
    name: 'Luca Dauphin',
    jobTitle: 'Chef',
    nationality: 'IT',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    telephone: '+41786197822',
    email: 'info@lucadauphin.ch',
    contactType: 'customer service',
    availableLanguage: ['French', 'Italian', 'English', 'German'],
    areaServed: 'CH',
  },
};
